--DROP CONSTRAINTS
-- Tabla CLASES_PROGRAMADAS
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT PK_CLA_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT NN_FE_CLA_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT NN_HOR_CLAS_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT NN_COD_SAL_CLA_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT NN_COD_CLA_CL_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT FK_ESTU_CLA_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT FK_NI_CLA_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT FK_CLA_CL_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT FK_SAL_CLA_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT FK_EST_CLA_PROG;
ALTER TABLE CLASES_PROGRAMADAS DROP CONSTRAINT FK_HO_CLA_PROG;
-- Tabla ESTUDIANTES_NIVELES
ALTER TABLE ESTUDIANTES_NIVELES DROP CONSTRAINT PK_EST_NI;
ALTER TABLE ESTUDIANTES_NIVELES DROP CONSTRAINT NN_DNI_EST;
ALTER TABLE ESTUDIANTES_NIVELES DROP CONSTRAINT NN_COD_NIVEL;
ALTER TABLE ESTUDIANTES_NIVELES DROP CONSTRAINT NN_NIVEL_ACT;
ALTER TABLE ESTUDIANTES_NIVELES DROP CONSTRAINT NN_FEC_LIMI;
ALTER TABLE ESTUDIANTES_NIVELES DROP CONSTRAINT FK_EST_NIVEL;
ALTER TABLE ESTUDIANTES_NIVELES DROP CONSTRAINT FK_NIVEL_EST;
-- Tabla CUPOS
ALTER TABLE CUPOS DROP CONSTRAINT PK_COD_CUPO;
ALTER TABLE CUPOS DROP CONSTRAINT NN_FEC_CUPO;
ALTER TABLE CUPOS DROP CONSTRAINT NN_COD_HO_CUPO;
ALTER TABLE CUPOS DROP CONSTRAINT NN_COD_NI_CUPO;
ALTER TABLE CUPOS DROP CONSTRAINT NN_COD_SAL_CUPO;
ALTER TABLE CUPOS DROP CONSTRAINT FK_HO_CUPOS;
ALTER TABLE CUPOS DROP CONSTRAINT FK_NI_CUPOS;
ALTER TABLE CUPOS DROP CONSTRAINT FK_SAL_CUPOS;
-- Tabla ADMINISTRADORES
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT PK_DNI_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_NOMBRE_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_APELLIDO1_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_TIPODOC_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_CORREO_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_SEXO_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_CONTRA_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_NACIM_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_ESTADO_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT NN_ROL_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT UK_CORREO_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT FK_TIPODOC_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT FK_SEXO_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT FK_ESTADO_ADMIN;
ALTER TABLE ADMINISTRADORES DROP CONSTRAINT FK_ROL_ADMIN;
-- Tabla ROLES
ALTER TABLE ROLES DROP CONSTRAINT PK_COD_ROL;
ALTER TABLE ROLES DROP CONSTRAINT NN_NOMBRE_ROL;
-- Tabla PROFESORES
ALTER TABLE PROFESORES DROP CONSTRAINT PK_DNI_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT NN_NOMBRE_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT NN_APELLIDO1_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT NN_TIPODOC_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT NN_CORREO_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT NN_SEXO_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT NN_CONTRA_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT NN_NACIM_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT NN_ESTADO_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT UK_CORREO_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT FK_TIPODOC_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT FK_SEXO_PROF;
ALTER TABLE PROFESORES DROP CONSTRAINT FK_ESTADO_PROF;
-- Tabla NOTAS
ALTER TABLE NOTAS DROP CONSTRAINT PK_NOTA;
ALTER TABLE NOTAS DROP CONSTRAINT NN_ESTUDIANTE_NOTA;
ALTER TABLE NOTAS DROP CONSTRAINT FK_NOTA_ESTUDIANTE;
ALTER TABLE NOTAS DROP CONSTRAINT FK_NOTA_EXAMEN_ORAL;
ALTER TABLE NOTAS DROP CONSTRAINT FK_NOTA_EXAMEN_ESCRITO;
-- Tabla ESTADOS_EXAMENES
ALTER TABLE ESTADOS_EXAMENES DROP CONSTRAINT PK_EST_EXAMEN;
ALTER TABLE ESTADOS_EXAMENES DROP CONSTRAINT NN_ESTADO_EXAMEN;
-- Tabla ESTADOS_CLASES
ALTER TABLE ESTADOS_CLASES DROP CONSTRAINT PK_COD_EST_CLA;
ALTER TABLE ESTADOS_CLASES DROP CONSTRAINT NN_NOM_EST_CLA;
-- Tabla RESPUESTAS_EXAMENES_ESCRITOS
ALTER TABLE RESPUESTAS_EXAMENES_ESCRITOS DROP CONSTRAINT PK_RESPUESTA_EXAMEN;
-- Tabla RESPUESTAS
ALTER TABLE RESPUESTAS DROP CONSTRAINT PK_RESPUESTA;
ALTER TABLE RESPUESTAS DROP CONSTRAINT NN_PREGUNTA_RESPUESTA;
ALTER TABLE RESPUESTAS DROP CONSTRAINT NN_CONTENIDO_RESPUESTA;
ALTER TABLE RESPUESTAS DROP CONSTRAINT NN_ACIERTO_RESPUESTA;
ALTER TABLE RESPUESTAS DROP CONSTRAINT FK_PREGUNTA_RESPUESTA;
-- Tabla PREGUNTAS
ALTER TABLE PREGUNTAS DROP CONSTRAINT PK_PREGUNTA;
ALTER TABLE PREGUNTAS DROP CONSTRAINT NN_EXAMEN_ESCRITO;
ALTER TABLE PREGUNTAS DROP CONSTRAINT NN_PREGUNTA;
ALTER TABLE PREGUNTAS DROP CONSTRAINT FK_EXAMEN_ESCRITO_PREGUNTA;
-- Tabla EXAMENES_ORALES
ALTER TABLE EXAMENES_ORALES DROP CONSTRAINT PK_EXAMEN_ORAL;
ALTER TABLE EXAMENES_ORALES DROP CONSTRAINT NN_ARCHIVO_URL;
ALTER TABLE EXAMENES_ORALES DROP CONSTRAINT FK_EXAMEN_ORAL;
-- Tabla EXAMENES_ESCRITOS
ALTER TABLE EXAMENES_ESCRITOS DROP CONSTRAINT PK_EXAMEN_ESCRITO;
ALTER TABLE EXAMENES_ESCRITOS DROP CONSTRAINT FK_EXAMEN_ESCRITO;
-- Tabla EXAMENES
ALTER TABLE EXAMENES DROP CONSTRAINT PK_NUM_EXAMEN;
ALTER TABLE EXAMENES DROP CONSTRAINT NN_UNIDADES_EXAMEN;
ALTER TABLE EXAMENES DROP CONSTRAINT NN_TEMATICA_EXAMEN;
ALTER TABLE EXAMENES DROP CONSTRAINT NN_CLASE_EXAMEN;
ALTER TABLE EXAMENES DROP CONSTRAINT NN_NIVEL_EXAMEN;
ALTER TABLE EXAMENES DROP CONSTRAINT FK_CLASE_EXAMEN;
ALTER TABLE EXAMENES DROP CONSTRAINT FK_NIVEL_EXAMEN;
-- Tabla CLASES
ALTER TABLE CLASES DROP CONSTRAINT PK_COD_CLA;
ALTER TABLE CLASES DROP CONSTRAINT NN_NUM_CLA;
ALTER TABLE CLASES DROP CONSTRAINT NN_DES_CLA;
ALTER TABLE CLASES DROP CONSTRAINT FK_COD_NI_CLA;
-- Tabla ESTUDIANTES
ALTER TABLE ESTUDIANTES DROP CONSTRAINT PK_DNI_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT NN_NOM_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT NN_APE1_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT NN_TIPODOC_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT NN_CORREO_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT NN_SEXO_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT NN_CONTRA_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT NN_NAC_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT NN_ESDO_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT UK_CORREO_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT FK_TIPODOC_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT FK_SEXO_EST;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT FK_ESDO_EST;
-- Tabla ESTADOS
ALTER TABLE ESTADOS DROP CONSTRAINT PK_CODIGO_ESTADO;
ALTER TABLE ESTADOS DROP CONSTRAINT NN_NOMBRE_ESTADO;
-- Tabla SEXOS
ALTER TABLE SEXOS DROP CONSTRAINT PK_CODIGO_SEX;
ALTER TABLE SEXOS DROP CONSTRAINT NN_NOMBRE_SEX;
-- Tabla TIPODOCUMENTOS
ALTER TABLE TIPODOCUMENTOS DROP CONSTRAINT PK_COD_TIPODOC;
ALTER TABLE TIPODOCUMENTOS DROP CONSTRAINT NN_NOM_TIPODOC;
-- Tabla NIVELES
ALTER TABLE NIVELES DROP CONSTRAINT PK_CODIGO_NIVEL;
ALTER TABLE NIVELES DROP CONSTRAINT NN_NIVEL;
-- Tabla HORAS
ALTER TABLE HORAS DROP CONSTRAINT PK_COD_HORA;
ALTER TABLE HORAS DROP CONSTRAINT NN_HO_INICIAL;
ALTER TABLE HORAS DROP CONSTRAINT NN_HO_FINAL;
-- Tabla SALONES
ALTER TABLE SALONES DROP CONSTRAINT PK_COD_SAL;
ALTER TABLE SALONES DROP CONSTRAINT NN_NUM_SAL;

--DROP TABLES
DROP TABLE CLASES_PROGRAMADAS;
DROP TABLE ESTUDIANTES_NIVELES;
DROP TABLE CUPOS;
DROP TABLE ADMINISTRADORES;
DROP TABLE ROLES;
DROP TABLE PROFESORES;
DROP TABLE NOTAS;
DROP TABLE ESTADOS_EXAMENES;
DROP TABLE ESTADOS_CLASES;
DROP TABLE RESPUESTAS_EXAMENES_ESCRITOS;
DROP TABLE RESPUESTAS;
DROP TABLE PREGUNTAS;
DROP TABLE EXAMENES_ORALES;
DROP TABLE EXAMENES_ESCRITOS;
DROP TABLE EXAMENES;
DROP TABLE CLASES;
DROP TABLE ESTUDIANTES;
DROP TABLE ESTADOS;
DROP TABLE SEXOS;
DROP TABLE TIPODOCUMENTOS;
DROP TABLE NIVELES;
DROP TABLE HORAS;
DROP TABLE SALONES;

--CREATE TABLES
CREATE TABLE ESTADOS(
	CODIGO_ESTADO NUMBER(1),
	NOMBRE_ESTADO VARCHAR2(50),
	CONSTRAINT PK_CODIGO_ESTADO PRIMARY KEY (CODIGO_ESTADO),
	CONSTRAINT NN_NOMBRE_ESTADO CHECK (NOMBRE_ESTADO IS NOT NULL)
) TABLESPACE ts_bdAcademy;

CREATE TABLE ROLES(
	CODIGO_ROL NUMBER(1),
	NOMBRE_ROL VARCHAR2(50),
	CONSTRAINT PK_COD_ROL PRIMARY KEY (CODIGO_ROL),
	CONSTRAINT NN_NOMBRE_ROL CHECK (NOMBRE_ROL IS NOT NULL)
) TABLESPACE ts_bdAcademy;

CREATE TABLE SEXOS (
	CODIGO_SEX NUMBER(1),
	NOMBRE_SEX VARCHAR2(20),
	CONSTRAINT PK_CODIGO_SEX PRIMARY KEY (CODIGO_SEX),
	CONSTRAINT NN_NOMBRE_SEX CHECK (NOMBRE_SEX IS NOT NULL)
) TABLESPACE ts_bdAcademy;


CREATE TABLE TIPODOCUMENTOS (
	CODIGO_TIPODOCUMENTO NUMBER(2),
	NOMBRE_DOCUMENTO VARCHAR2(50),
	CONSTRAINT PK_COD_TIPODOC PRIMARY KEY (CODIGO_TIPODOCUMENTO),
	CONSTRAINT NN_NOM_TIPODOC CHECK (NOMBRE_DOCUMENTO IS NOT NULL)
) TABLESPACE ts_bdAcademy;


CREATE TABLE NIVELES (
	CODIGO_NIVEL NUMBER(1),
	NIVEL VARCHAR2(5),
	CONSTRAINT PK_CODIGO_NIVEL PRIMARY KEY (CODIGO_NIVEL),
	CONSTRAINT NN_NIVEL CHECK (NIVEL IS NOT NULL)
) TABLESPACE ts_bdAcademy;


CREATE TABLE ESTADOS_CLASES(
	CODIGO_ESTADO_CLASE NUMBER(1),
	NOMBRE_ESTADO_CLASE VARCHAR2(20),
	CONSTRAINT PK_COD_EST_CLA PRIMARY KEY (CODIGO_ESTADO_CLASE),
	CONSTRAINT NN_NOM_EST_CLA CHECK (NOMBRE_ESTADO_CLASE IS NOT NULL)
) TABLESPACE ts_bdAcademy;


CREATE TABLE ESTUDIANTES (
	NOMBRE_ESTUDIANTE VARCHAR2(50),
	APELLIDO1_ESTUDIANTE VARCHAR2(50),
	APELLIDO2_ESTUDIANTE VARCHAR2(50),
	TIPODOCUMENTO_ESTUDIANTE NUMBER(2),
	DNI_ESTUDIANTE VARCHAR2(20),
	CORREO_ESTUDIANTE VARCHAR2(100),
	SEXO_ESTUDIANTE NUMBER(1),
	CONTRASENNA_ESTUDIANTE VARCHAR2(50),
	FECHA_NACIMIENTO_ESTUDIANTE DATE,
	ESTADO_ESTUDIANTE NUMBER(1),
	CONSTRAINT PK_DNI_EST PRIMARY KEY (DNI_ESTUDIANTE),
	CONSTRAINT NN_NOM_EST CHECK (NOMBRE_ESTUDIANTE IS NOT NULL),
	CONSTRAINT NN_APE1_EST CHECK (APELLIDO1_ESTUDIANTE IS NOT NULL),
	CONSTRAINT NN_TIPODOC_EST CHECK (TIPODOCUMENTO_ESTUDIANTE IS NOT NULL),
	CONSTRAINT NN_CORREO_EST CHECK (CORREO_ESTUDIANTE IS NOT NULL),
	CONSTRAINT NN_SEXO_EST CHECK (SEXO_ESTUDIANTE IS NOT NULL),
	CONSTRAINT NN_CONTRA_EST CHECK (CONTRASENNA_ESTUDIANTE IS NOT NULL),
	CONSTRAINT NN_NAC_EST CHECK (FECHA_NACIMIENTO_ESTUDIANTE IS NOT NULL),
	CONSTRAINT NN_ESDO_EST CHECK (ESTADO_ESTUDIANTE IS NOT NULL),
	CONSTRAINT UK_CORREO_EST UNIQUE (CORREO_ESTUDIANTE),
	CONSTRAINT FK_TIPODOC_EST FOREIGN KEY (TIPODOCUMENTO_ESTUDIANTE) REFERENCES TIPODOCUMENTOS(CODIGO_TIPODOCUMENTO),
	CONSTRAINT FK_SEXO_EST FOREIGN KEY (SEXO_ESTUDIANTE) REFERENCES SEXOS(CODIGO_SEX),
	CONSTRAINT FK_ESDO_EST FOREIGN KEY (ESTADO_ESTUDIANTE) REFERENCES ESTADOS(CODIGO_ESTADO)
) TABLESPACE  ts_bdAcademy;

CREATE TABLE PROFESORES (
	NOMBRE_PROFESOR VARCHAR2(50),
	APELLIDO1_PROFESOR VARCHAR2(50),
	APELLIDO2_PROFESOR VARCHAR2(50),
	TIPODOCUMENTO_PROFESOR NUMBER(2),
	DNI_PROFESOR VARCHAR2(20),
	CORREO_PROFESOR VARCHAR2(100),
	SEXO_PROFESOR NUMBER(1),
	CONTRASENNA_PROFESOR VARCHAR2(20),
	FECHA_NACIMIENTO_PROFESOR DATE,
	ESTADO_PROFESOR NUMBER(1),
	CONSTRAINT PK_DNI_PROF PRIMARY KEY (DNI_PROFESOR),
	CONSTRAINT NN_NOM_PROF CHECK (NOMBRE_PROFESOR IS NOT NULL),
	CONSTRAINT NN_APE1_PROF CHECK (APELLIDO1_PROFESOR IS NOT NULL),
	CONSTRAINT NN_TIPODOC_PROF CHECK (TIPODOCUMENTO_PROFESOR IS NOT NULL),
	CONSTRAINT NN_CORREO_PROF CHECK (CORREO_PROFESOR IS NOT NULL),
	CONSTRAINT UK_CORREO_PROF UNIQUE (CORREO_PROFESOR),
	CONSTRAINT FK_TIPODOC_PROF FOREIGN KEY (TIPODOCUMENTO_PROFESOR) REFERENCES TIPODOCUMENTOS(CODIGO_TIPODOCUMENTO)
);

CREATE TABLE ADMINISTRADORES (
	NOMBRE_ADMIN VARCHAR2(50),
	APELLIDO1_ADMIN VARCHAR2(50),
	APELLIDO2_ADMIN VARCHAR2(50),
	TIPODOCUMENTO_ADMIN NUMBER(3),
	DNI_ADMIN VARCHAR2(20),
	CORREO_ADMIN VARCHAR2(100),
	SEXO_ADMIN NUMBER(2),
	CONTRASENA_ADMIN VARCHAR2(100),
	FECHA_NACIMIENTO_ADMIN DATE,
	ESTADO_ADMIN NUMBER(1),
	ROL_ADMIN NUMBER(1),
	CONSTRAINT PK_DNI_ADMINISTRADOR PRIMARY KEY (DNI_ADMIN),
	CONSTRAINT NN_NOMBRE_ADMIN CHECK (NOMBRE_ADMIN IS NOT NULL),
	CONSTRAINT NN_APELLIDO1_ADMIN CHECK (APELLIDO1_ADMIN IS NOT NULL),
	CONSTRAINT NN_TIPODOC_ADMIN CHECK (TIPODOCUMENTO_ADMIN IS NOT NULL),
	CONSTRAINT NN_CORREO_ADMIN CHECK (CORREO_ADMIN IS NOT NULL),
	CONSTRAINT NN_SEXO_ADMIN CHECK (SEXO_ADMIN IS NOT NULL),
	CONSTRAINT NN_CONTRA_ADMIN CHECK (CONTRASENA_ADMIN IS NOT NULL),
	CONSTRAINT NN_NACIM_ADMIN CHECK (FECHA_NACIMIENTO_ADMIN IS NOT NULL),
	CONSTRAINT NN_ESTADO_ADMIN CHECK (ESTADO_ADMIN IS NOT NULL),
	CONSTRAINT NN_ROL_ADMIN CHECK (ROL_ADMIN IS NOT NULL),
	CONSTRAINT UK_CORREO_ADMIN UNIQUE (CORREO_ADMIN),
	CONSTRAINT FK_TIPODOC_ADMIN FOREIGN KEY (TIPODOCUMENTO_ADMIN) REFERENCES TIPODOCUMENTOS(CODIGO_TIPODOCUMENTO),
	CONSTRAINT FK_SEXO_ADMIN FOREIGN KEY (SEXO_ADMIN) REFERENCES SEXOS(CODIGO_SEX),
	CONSTRAINT FK_ESTADO_ADMIN FOREIGN KEY (ESTADO_ADMIN) REFERENCES ESTADOS(CODIGO_ESTADO),
CONSTRAINT FK_ROL_ADMIN FOREIGN KEY (ROL_ADMIN) REFERENCES ROLES(CODIGO_ROL)
) TABLESPACE ts_bdAcademy;

CREATE TABLE ESTUDIANTES_NIVELES (
	DNI_ESTUDIANTE VARCHAR2(20),
	CODIGO_NIVEL NUMBER(1),
	NIVEL_ACTUAL VARCHAR2(10),
	FECHA_LIMITE DATE,
	CONSTRAINT PK_EST_NI PRIMARY KEY (DNI_ESTUDIANTE, CODIGO_NIVEL),
	CONSTRAINT NN_DNI_EST CHECK (DNI_ESTUDIANTE IS NOT NULL),
	CONSTRAINT NN_COD_NIVEL CHECK (CODIGO_NIVEL IS NOT NULL),
	CONSTRAINT NN_NIVEL_ACT CHECK (NIVEL_ACTUAL IS NOT NULL),
	CONSTRAINT NN_FEC_LIM CHECK (FECHA_LIMITE IS NOT NULL),
	CONSTRAINT FK_EST_NIVEL FOREIGN KEY (DNI_ESTUDIANTE) REFERENCES ESTUDIANTES(DNI_ESTUDIANTE),
	CONSTRAINT FK_NIVEL_EST FOREIGN KEY (CODIGO_NIVEL) REFERENCES NIVELES(CODIGO_NIVEL)
) TABLESPACE ts_bdAcademy;


CREATE TABLE CLASES (
	CODIGO_CLASE VARCHAR2(10),
	NUMERO_CLASE NUMBER(2),
	DESCRIPCION_CLASE VARCHAR2(100),
	CODIGO_NIVEL_CLASE NUMBER(1),
	CONSTRAINT PK_COD_CLA PRIMARY KEY (CODIGO_CLASE),
	CONSTRAINT NN_NUM_CLA CHECK (NUMERO_CLASE IS NOT NULL),
	CONSTRAINT NN_DES_CLA CHECK (DESCRIPCION_CLASE IS NOT NULL),
	CONSTRAINT FK_COD_NI_CLA FOREIGN KEY (CODIGO_NIVEL_CLASE) REFERENCES NIVELES(CODIGO_NIVEL)
) TABLESPACE ts_bdAcademy;


CREATE TABLE SALONES (
	CODIGO_SALON NUMBER(2),
	NUMERO_SALON NUMBER(3),
	CAPACIDAD_SALON NUMBER(1),
	CONSTRAINT PK_COD_SAL PRIMARY KEY (CODIGO_SALON),
	CONSTRAINT NN_NUM_SAL CHECK (NUMERO_SALON IS NOT NULL)
) TABLESPACE ts_bdAcademy;


CREATE TABLE HORAS(
	CODIGO_HORA NUMBER(2),
	HORA_INICIAL VARCHAR2(10),
	HORA_FINAL VARCHAR2(10),
	CONSTRAINT PK_COD_HORA PRIMARY KEY (CODIGO_HORA),
	CONSTRAINT NN_HO_INICIAL CHECK (HORA_INICIAL IS NOT NULL),
CONSTRAINT NN_HO_FINAL CHECK (HORA_FINAL IS NOT NULL)
) TABLESPACE ts_bdAcademy;


CREATE TABLE CLASES_PROGRAMADAS (
	CODIGO_CLASE_PROGRAMADA NUMBER(3),
	DNI_ESTUDIANTE VARCHAR2(20),
	FECHA_CLASE_PROGRAMADA DATE,
	HORA_CLASE_PROGRAMADA NUMBER(2),
	CODIGO_NIVEL NUMBER(1),
	CODIGO_CLASE VARCHAR2(10),
	CODIGO_SALON NUMBER(3),
	ESTADO_CLASE_PROGRAMADA NUMBER(1),
	CONSTRAINT PK_CLA_PROG PRIMARY KEY (CODIGO_CLASE_PROGRAMADA)
) TABLESPACE ts_bdAcademy;

ALTER TABLE CLASES_PROGRAMADAS
ADD CONSTRAINT FK_ESTU_CLA_PROG
FOREIGN KEY (DNI_ESTUDIANTE, CODIGO_NIVEL)
REFERENCES ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL);

ALTER TABLE CLASES_PROGRAMADAS
ADD CONSTRAINT FK_NI_CLA_PROG
FOREIGN KEY (CODIGO_NIVEL)
REFERENCES NIVELES(CODIGO_NIVEL);

ALTER TABLE CLASES_PROGRAMADAS
ADD CONSTRAINT FK_CLA_CL_PROG
FOREIGN KEY (CODIGO_CLASE)
REFERENCES CLASES(CODIGO_CLASE);

ALTER TABLE CLASES_PROGRAMADAS
ADD CONSTRAINT FK_SAL_CLA_PROG
FOREIGN KEY (CODIGO_SALON)
REFERENCES SALONES(CODIGO_SALON);

ALTER TABLE CLASES_PROGRAMADAS
ADD CONSTRAINT FK_EST_CLA_PROG
FOREIGN KEY (ESTADO_CLASE_PROGRAMADA)
REFERENCES ESTADOS_CLASES(CODIGO_ESTADO_CLASE);

ALTER TABLE CLASES_PROGRAMADAS
ADD CONSTRAINT FK_HO_CLA_PROG
FOREIGN KEY (HORA_CLASE_PROGRAMADA)
REFERENCES HORAS(CODIGO_HORA);


CREATE TABLE CUPOS (
	CODIGO_CUPO NUMBER(5),
	FECHA_CUPO DATE,
	CODIGO_HORA NUMBER(2),
	CODIGO_NIVEL NUMBER(1),
	CODIGO_SALON NUMBER(3),
	ESTUDIANTES_REGISTRADOS NUMBER(1) DEFAULT 0,
	CONSTRAINT PK_COD_CUPO PRIMARY KEY (CODIGO_CUPO),
	CONSTRAINT NN_FEC_CUPO CHECK (FECHA_CUPO IS NOT NULL),
	CONSTRAINT NN_COD_HO_CUPO CHECK (CODIGO_HORA IS NOT NULL),
	CONSTRAINT NN_COD_NI_CUPO CHECK (CODIGO_NIVEL IS NOT NULL),
	CONSTRAINT NN_COD_SAL_CUPO CHECK (CODIGO_SALON IS NOT NULL),
	CONSTRAINT FK_HO_CUPOS FOREIGN KEY (CODIGO_HORA) REFERENCES HORAS(CODIGO_HORA),
	CONSTRAINT FK_NI_CUPOS FOREIGN KEY (CODIGO_NIVEL) REFERENCES NIVELES(CODIGO_NIVEL),
	CONSTRAINT FK_SAL_CUPOS FOREIGN KEY (CODIGO_SALON) REFERENCES SALONES(CODIGO_SALON)
) TABLESPACE ts_bdAcademy;

CREATE TABLE EXAMENES (
	NUMERO_EXAMEN NUMBER(2),
	UNIDADES_EXAMEN VARCHAR2(50),
	TEMATICA_EXAMEN VARCHAR2(50),
	CODIGO_CLASE_EXAMEN VARCHAR2(10),
	CODIGO_NIVEL_EXAMEN NUMBER(1),
	CONSTRAINT PK_NUM_EXAM PRIMARY KEY (NUMERO_EXAMEN),
	CONSTRAINT NN_UNIDADES_EXAM CHECK (UNIDADES_EXAMEN IS NOT NULL),
	CONSTRAINT NN_TEMATICA_EXAM CHECK (TEMATICA_EXAMEN IS NOT NULL),
	CONSTRAINT NN_CLASE_EXAM CHECK (CODIGO_CLASE_EXAMEN IS NOT NULL),
	CONSTRAINT NN_NIVEL_EXAM CHECK (CODIGO_NIVEL_EXAMEN IS NOT NULL),
	CONSTRAINT FK_CLASE_EXAM FOREIGN KEY (CODIGO_CLASE_EXAMEN)
    	REFERENCES CLASES(CODIGO_CLASE),
	CONSTRAINT FK_NIVEL_EXAM FOREIGN KEY (CODIGO_NIVEL_EXAMEN)
    	REFERENCES NIVELES(CODIGO_NIVEL)
) TABLESPACE ts_bdAcademy;

CREATE TABLE EXAMENES_ESCRITOS (
	CODIGO_EXAMEN_ESCRITO NUMBER(2),
	CODIGO_EXAMEN NUMBER(2),
	CONSTRAINT PK_EXAMEN_ESCRITO PRIMARY KEY (CODIGO_EXAMEN_ESCRITO),
	CONSTRAINT FK_EXAMEN_ESCRITO FOREIGN KEY (CODIGO_EXAMEN) REFERENCES EXAMENES(NUMERO_EXAMEN)
) TABLESPACE ts_bdAcademy;

CREATE TABLE PREGUNTAS (
	CODIGO_PREGUNTA NUMBER(4),
	CODIGO_EXAMEN_ESCRITO NUMBER(2),
	PREGUNTA VARCHAR2(255),
	CONSTRAINT PK_PREGUNTA PRIMARY KEY (CODIGO_PREGUNTA),
  CONSTRAINT NN_EXAMEN_ESCRITO CHECK (CODIGO_EXAMEN_ESCRITO IS NOT NULL),
	CONSTRAINT NN_PREGUNTA CHECK (PREGUNTA IS NOT NULL),
	CONSTRAINT FK_EXAMEN_ESCRITO_PREGUNTA FOREIGN KEY (CODIGO_EXAMEN_ESCRITO) REFERENCES EXAMENES_ESCRITOS(CODIGO_EXAMEN_ESCRITO)
) TABLESPACE ts_bdAcademy;

CREATE TABLE RESPUESTAS (
	CODIGO_RESPUESTA NUMBER(4),
	CODIGO_PREGUNTA_RESPUESTA NUMBER(4),
	CONTENIDO_RESPUESTA VARCHAR2(255),
	ACIERTO_RESPUESTA VARCHAR2(10),
	CONSTRAINT PK_RESPUESTA PRIMARY KEY (CODIGO_RESPUESTA),
	CONSTRAINT NN_PREGUNTA_RESPUESTA CHECK (CODIGO_PREGUNTA_RESPUESTA IS NOT NULL),
	CONSTRAINT NN_CONTENIDO_RESPUESTA CHECK (CONTENIDO_RESPUESTA IS NOT NULL),
	CONSTRAINT NN_ACIERTO_RESPUESTA CHECK (ACIERTO_RESPUESTA IS NOT NULL),
	CONSTRAINT FK_PREGUNTA_RESPUESTA FOREIGN KEY (CODIGO_PREGUNTA_RESPUESTA) REFERENCES PREGUNTAS(CODIGO_PREGUNTA)
) TABLESPACE ts_bdAcademy;

CREATE TABLE EXAMENES_ORALES (
	CODIGO_EXAMEN_ORAL NUMBER(2),
	CODIGO_EXAMEN NUMBER(2),
	ARCHIVO_URL VARCHAR2(255),
	CONSTRAINT PK_EXAMEN_ORAL PRIMARY KEY (CODIGO_EXAMEN_ORAL),
	CONSTRAINT NN_ARCHIVO_URL CHECK (ARCHIVO_URL IS NOT NULL),
	CONSTRAINT FK_EXAMEN_ORAL FOREIGN KEY (CODIGO_EXAMEN) REFERENCES EXAMENES(NUMERO_EXAMEN)
) TABLESPACE ts_bdAcademy;

CREATE TABLE ESTADOS_EXAMENES (
	CODIGO_ESTADO NUMBER(1),
	ESTADO_EXAMEN VARCHAR2(15),
	CONSTRAINT PK_ESTADO_EXAMEN PRIMARY KEY (CODIGO_ESTADO),
CONSTRAINT NN_ESTADO_EXAMEN CHECK (ESTADO_EXAMEN IS NOT NULL)
)TABLESPACE ts_bdAcademy;

CREATE TABLE NOTAS (
	CODIGO_NOTA NUMBER(3),
	DNI_ESTUDIANTE VARCHAR2(20),
	CODIGO_EXAMEN_ORAL NUMBER(2),
	NOTA_EXAMEN_ORAL DECIMAL(3, 2) CHECK (NOTA_EXAMEN_ORAL >= 0.0 AND NOTA_EXAMEN_ORAL <= 5.0),
	FECHA_EVALUACION_EXAMEN_ORAL DATE,
	CODIGO_EXAMEN_ESCRITO NUMBER(2),
	NOTA_EXAMEN_ESCRITO DECIMAL(3, 2) CHECK (NOTA_EXAMEN_ESCRITO >= 0.0 AND NOTA_EXAMEN_ESCRITO <= 5.0),
	FECHA_EVALUACION_EXAMEN_ESCRITO DATE,
	ESTADO NUMBER(1),
	CONSTRAINT PK_NOTA PRIMARY KEY (CODIGO_NOTA),
	CONSTRAINT NN_ESTUDIANTE_NOTA CHECK (DNI_ESTUDIANTE IS NOT NULL),
	CONSTRAINT FK_NOTA_ESTUDIANTE FOREIGN KEY (DNI_ESTUDIANTE) REFERENCES ESTUDIANTES(DNI_ESTUDIANTE),
	CONSTRAINT FK_NOTA_EXAMEN_ORAL FOREIGN KEY (CODIGO_EXAMEN_ORAL) REFERENCES EXAMENES_ORALES(CODIGO_EXAMEN_ORAL),
	CONSTRAINT FK_NOTA_EXAMEN_ESCRITO FOREIGN KEY (CODIGO_EXAMEN_ESCRITO) REFERENCES EXAMENES_ESCRITOS(CODIGO_EXAMEN_ESCRITO),
	CONSTRAINT FK_EST_EXAMEN FOREIGN KEY (ESTADO) REFERENCES ESTADOS_EXAMENES(CODIGO_ESTADO)
) TABLESPACE ts_bdAcademy;

CREATE TABLE RESPUESTAS_EXAMENES_ESCRITOS (
	DNI_ESTUDIANTE VARCHAR2(20), 
	CODIGO_EXAMEN_ESCRITO NUMBER(2),
	CODIGO_PREGUNTA NUMBER(4),	
	RESPUESTA_ESTUDIANTE	NUMBER(4), 
	CORRECTA CHAR(1) CHECK (CORRECTA IN ('S', 'N')), 
	CONSTRAINT PK_RESPUESTA_EXAMEN PRIMARY KEY (DNI_ESTUDIANTE, CODIGO_EXAMEN_ESCRITO, CODIGO_PREGUNTA),
	FOREIGN KEY (DNI_ESTUDIANTE) REFERENCES ESTUDIANTES(DNI_ESTUDIANTE),
	FOREIGN KEY (CODIGO_EXAMEN_ESCRITO) REFERENCES EXAMENES_ESCRITOS(CODIGO_EXAMEN_ESCRITO),
	FOREIGN KEY (CODIGO_PREGUNTA) REFERENCES PREGUNTAS(CODIGO_PREGUNTA)
) TABLESPACE ts_bdAcademy;

--INSERT REGISTROS
INSERT INTO ESTADOS (CODIGO_ESTADO, NOMBRE_ESTADO) VALUES (1, 'Activo');
INSERT INTO ESTADOS (CODIGO_ESTADO, NOMBRE_ESTADO) VALUES (2, 'Inactivo');

INSERT INTO ROLES (CODIGO_ROL, NOMBRE_ROL) VALUES (1, 'Administrador');
INSERT INTO ROLES (CODIGO_ROL, NOMBRE_ROL) VALUES (2, 'Superadministrador');

INSERT INTO SEXOS (CODIGO_SEX, NOMBRE_SEX) VALUES (1, 'Masculino');
INSERT INTO SEXOS (CODIGO_SEX, NOMBRE_SEX) VALUES (2, 'Femenino');

INSERT INTO TIPODOCUMENTOS (CODIGO_TIPODOCUMENTO, NOMBRE_DOCUMENTO) VALUES (1, 'C�dula de Ciudadan�a');
INSERT INTO TIPODOCUMENTOS (CODIGO_TIPODOCUMENTO, NOMBRE_DOCUMENTO) VALUES (2, 'Tarjeta de Identidad');
INSERT INTO TIPODOCUMENTOS (CODIGO_TIPODOCUMENTO, NOMBRE_DOCUMENTO) VALUES (3, 'Pasaporte');

INSERT INTO NIVELES (CODIGO_NIVEL, NIVEL) VALUES (1, 'A1');
INSERT INTO NIVELES (CODIGO_NIVEL, NIVEL) VALUES (2, 'A2');
INSERT INTO NIVELES (CODIGO_NIVEL, NIVEL) VALUES (3, 'B1');

INSERT INTO ESTADOS_CLASES (CODIGO_ESTADO_CLASE, NOMBRE_ESTADO_CLASE) VALUES (1, 'Pendiente');
INSERT INTO ESTADOS_CLASES (CODIGO_ESTADO_CLASE, NOMBRE_ESTADO_CLASE) VALUES (2, 'Programada');
INSERT INTO ESTADOS_CLASES (CODIGO_ESTADO_CLASE, NOMBRE_ESTADO_CLASE) VALUES (3, 'Finalizada');

INSERT INTO ADMINISTRADORES (
	NOMBRE_ADMIN, APELLIDO1_ADMIN, APELLIDO2_ADMIN,
	TIPODOCUMENTO_ADMIN, DNI_ADMIN, CORREO_ADMIN,
	SEXO_ADMIN, CONTRASENA_ADMIN, FECHA_NACIMIENTO_ADMIN,
	ESTADO_ADMIN, ROL_ADMIN
)
VALUES
('Carolina', 'Mart�nez', 'R�os', 1, '44556677', 'carolina.martinez@example.com', 2, 'adminpass', TO_DATE('1992-05-10', 'YYYY-MM-DD'), 1, 1);

INSERT INTO ADMINISTRADORES (
	NOMBRE_ADMIN, APELLIDO1_ADMIN, APELLIDO2_ADMIN,
	TIPODOCUMENTO_ADMIN, DNI_ADMIN, CORREO_ADMIN,
	SEXO_ADMIN, CONTRASENA_ADMIN, FECHA_NACIMIENTO_ADMIN,
	ESTADO_ADMIN, ROL_ADMIN
)
VALUES
('Jos�', 'Londo�o', 'Quintero', 2, '55667788', 'jose.londono@example.com', 1, 'admin123', TO_DATE('1980-11-02', 'YYYY-MM-DD'), 1, 2);

INSERT INTO ADMINISTRADORES (
	NOMBRE_ADMIN, APELLIDO1_ADMIN, APELLIDO2_ADMIN,
	TIPODOCUMENTO_ADMIN, DNI_ADMIN, CORREO_ADMIN,
	SEXO_ADMIN, CONTRASENA_ADMIN, FECHA_NACIMIENTO_ADMIN,
	ESTADO_ADMIN, ROL_ADMIN
)
VALUES
('Ana', 'P�rez', 'Gonz�lez', 1, '66778899', 'ana.perez@example.com', 2, 'anaadmin', TO_DATE('1995-04-18', 'YYYY-MM-DD'), 1, 1);

INSERT INTO PROFESORES (
	NOMBRE_PROFESOR, APELLIDO1_PROFESOR, APELLIDO2_PROFESOR,
	TIPODOCUMENTO_PROFESOR, DNI_PROFESOR, CORREO_PROFESOR,
	SEXO_PROFESOR, CONTRASENNA_PROFESOR, FECHA_NACIMIENTO_PROFESOR,
	ESTADO_PROFESOR
)
VALUES
('Andr�s', 'Torres', 'M�ndez', 1, '11223344', 'andres.torres@example.com', 1, 'andrespass', TO_DATE('1985-03-15', 'YYYY-MM-DD'), 1);

INSERT INTO PROFESORES (
	NOMBRE_PROFESOR, APELLIDO1_PROFESOR, APELLIDO2_PROFESOR,
	TIPODOCUMENTO_PROFESOR, DNI_PROFESOR, CORREO_PROFESOR,
	SEXO_PROFESOR, CONTRASENNA_PROFESOR, FECHA_NACIMIENTO_PROFESOR,
	ESTADO_PROFESOR
)
VALUES
('Paula', 'Restrepo', 'D�az', 2, '22334455', 'paula.restrepo@example.com', 2, 'paulapass', TO_DATE('1990-07-21', 'YYYY-MM-DD'), 1);

INSERT INTO PROFESORES (
	NOMBRE_PROFESOR, APELLIDO1_PROFESOR, APELLIDO2_PROFESOR,
	TIPODOCUMENTO_PROFESOR, DNI_PROFESOR, CORREO_PROFESOR,
	SEXO_PROFESOR, CONTRASENNA_PROFESOR, FECHA_NACIMIENTO_PROFESOR,
	ESTADO_PROFESOR
)
VALUES
('Miguel', 'Vargas', 'L�pez', 1, '33445566', 'miguel.vargas@example.com', 1, 'miguelpass', TO_DATE('1978-12-05', 'YYYY-MM-DD'), 2);

INSERT INTO ESTUDIANTES (NOMBRE_ESTUDIANTE, APELLIDO1_ESTUDIANTE, APELLIDO2_ESTUDIANTE,
	TIPODOCUMENTO_ESTUDIANTE, DNI_ESTUDIANTE, CORREO_ESTUDIANTE, SEXO_ESTUDIANTE, CONTRASENNA_ESTUDIANTE,
	FECHA_NACIMIENTO_ESTUDIANTE, ESTADO_ESTUDIANTE)
VALUES ('Carlos', 'P�rez', 'G�mez', 1, '1234567', 'carlos@gmail.com', 1, 'carlos123', TO_DATE('2000-05-10', 'YYYY-MM-DD'), 1);
INSERT INTO ESTUDIANTES (NOMBRE_ESTUDIANTE, APELLIDO1_ESTUDIANTE, APELLIDO2_ESTUDIANTE,
                     	TIPODOCUMENTO_ESTUDIANTE, DNI_ESTUDIANTE, CORREO_ESTUDIANTE,
                     	SEXO_ESTUDIANTE, CONTRASENNA_ESTUDIANTE, FECHA_NACIMIENTO_ESTUDIANTE,
                     	ESTADO_ESTUDIANTE)
VALUES ('Laura', 'G�mez', 'Ram�rez', 1, '12345678', 'laura.gomez@example.com',
    	2, 'password123', TO_DATE('2001-06-15', 'YYYY-MM-DD'), 1);
INSERT INTO ESTUDIANTES (NOMBRE_ESTUDIANTE, APELLIDO1_ESTUDIANTE, APELLIDO2_ESTUDIANTE,
                     	TIPODOCUMENTO_ESTUDIANTE, DNI_ESTUDIANTE, CORREO_ESTUDIANTE,
                     	SEXO_ESTUDIANTE, CONTRASENNA_ESTUDIANTE, FECHA_NACIMIENTO_ESTUDIANTE,
                     	ESTADO_ESTUDIANTE)
VALUES ('Carlos', 'P�rez', 'Mart�nez', 2, '87654321', 'carlos.perez@example.com',
    	1, 'pass789', TO_DATE('2000-04-20', 'YYYY-MM-DD'), 1);
INSERT INTO ESTUDIANTES (NOMBRE_ESTUDIANTE, APELLIDO1_ESTUDIANTE, APELLIDO2_ESTUDIANTE,
                     	TIPODOCUMENTO_ESTUDIANTE, DNI_ESTUDIANTE, CORREO_ESTUDIANTE,
                     	SEXO_ESTUDIANTE, CONTRASENNA_ESTUDIANTE, FECHA_NACIMIENTO_ESTUDIANTE,
                     	ESTADO_ESTUDIANTE)
VALUES ('Mariana', 'L�pez', 'Torres', 1, '23456789', 'mariana.lopez@example.com',
    	2, 'securepass', TO_DATE('2002-11-10', 'YYYY-MM-DD'), 1);
INSERT INTO ESTUDIANTES (NOMBRE_ESTUDIANTE, APELLIDO1_ESTUDIANTE, APELLIDO2_ESTUDIANTE,
                     	TIPODOCUMENTO_ESTUDIANTE, DNI_ESTUDIANTE, CORREO_ESTUDIANTE,
                     	SEXO_ESTUDIANTE, CONTRASENNA_ESTUDIANTE, FECHA_NACIMIENTO_ESTUDIANTE,
                     	ESTADO_ESTUDIANTE)
VALUES ('Jorge', 'Ram�rez', 'Ortiz', 2, '98765432', 'jorge.ramirez@example.com',
    	1, 'mypassword', TO_DATE('1999-02-05', 'YYYY-MM-DD'), 1);
INSERT INTO ESTUDIANTES (NOMBRE_ESTUDIANTE, APELLIDO1_ESTUDIANTE, APELLIDO2_ESTUDIANTE,
                     	TIPODOCUMENTO_ESTUDIANTE, DNI_ESTUDIANTE, CORREO_ESTUDIANTE,
                     	SEXO_ESTUDIANTE, CONTRASENNA_ESTUDIANTE, FECHA_NACIMIENTO_ESTUDIANTE,
                     	ESTADO_ESTUDIANTE)
VALUES ('Sof�a', 'R�os', 'Fern�ndez', 1, '54321678', 'sofia.rios@example.com',
    	2, 'superpass', TO_DATE('2003-09-25', 'YYYY-MM-DD'), 1);
INSERT INTO ESTUDIANTES (NOMBRE_ESTUDIANTE, APELLIDO1_ESTUDIANTE, APELLIDO2_ESTUDIANTE,
                     	TIPODOCUMENTO_ESTUDIANTE, DNI_ESTUDIANTE, CORREO_ESTUDIANTE,
                     	SEXO_ESTUDIANTE, CONTRASENNA_ESTUDIANTE, FECHA_NACIMIENTO_ESTUDIANTE,
                     	ESTADO_ESTUDIANTE)
VALUES ('Manuela', 'Gaviria', 'Moreno', 1, '1000412597', 'mangav@example.com',
    	2, 'superpass', TO_DATE('2002-07-05', 'YYYY-MM-DD'), 1);


INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('1234567', 1, 'true', TO_DATE('2024-12-31', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('12345678', 1, 'true', TO_DATE('2025-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('87654321', 1, 'true', TO_DATE('2025-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('23456789', 1, 'true', TO_DATE('2025-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('98765432', 1, 'true', TO_DATE('2025-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('54321678', 1, 'true', TO_DATE('2025-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('1000412597', 1, 'true', TO_DATE('2025-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('1234567', 2, 'false', TO_DATE('2025-12-31', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('12345678', 2, 'false', TO_DATE('2026-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('87654321', 2, 'false', TO_DATE('2026-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('23456789', 2, 'false', TO_DATE('2026-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('98765432', 2, 'false', TO_DATE('2026-06-30', 'YYYY-MM-DD'));
INSERT INTO ESTUDIANTES_NIVELES (DNI_ESTUDIANTE, CODIGO_NIVEL, NIVEL_ACTUAL, FECHA_LIMITE)
VALUES ('54321678', 2, 'false', TO_DATE('2026-06-30', 'YYYY-MM-DD'));

INSERT INTO CLASES (CODIGO_CLASE, NUMERO_CLASE, DESCRIPCION_CLASE, CODIGO_NIVEL_CLASE)
VALUES ('CA101', 1, 'Introducci�n al Ingl�s', 1);
INSERT INTO CLASES (CODIGO_CLASE, NUMERO_CLASE, DESCRIPCION_CLASE, CODIGO_NIVEL_CLASE)
VALUES ('CA102', 2, 'Vocabulario B�sico', 1);
INSERT INTO CLASES (CODIGO_CLASE, NUMERO_CLASE, DESCRIPCION_CLASE, CODIGO_NIVEL_CLASE)
VALUES ('CA103', 3, 'Conversaciones Simples', 1);
INSERT INTO CLASES (CODIGO_CLASE, NUMERO_CLASE, DESCRIPCION_CLASE, CODIGO_NIVEL_CLASE)
VALUES ('CA104', 4, 'Gram�tica B�sica', 1);
INSERT INTO CLASES (CODIGO_CLASE, NUMERO_CLASE, DESCRIPCION_CLASE, CODIGO_NIVEL_CLASE)
VALUES ('CA105', 5, 'Lectura Intermedia', 1);
INSERT INTO CLASES (CODIGO_CLASE, NUMERO_CLASE, DESCRIPCION_CLASE, CODIGO_NIVEL_CLASE)
VALUES ('CA106', 6, 'Redacci�n de Ensayos', 1);

INSERT INTO SALONES (CODIGO_SALON, NUMERO_SALON, CAPACIDAD_SALON) VALUES (1, 101, 6);
INSERT INTO SALONES (CODIGO_SALON, NUMERO_SALON, CAPACIDAD_SALON) VALUES (2, 102, 6);

INSERT INTO HORAS (CODIGO_HORA, HORA_INICIAL, HORA_FINAL) VALUES (1, '08:00', '10:00');
INSERT INTO HORAS (CODIGO_HORA, HORA_INICIAL, HORA_FINAL) VALUES (2, '10:00', '12:00');

INSERT INTO CLASES_PROGRAMADAS (CODIGO_CLASE_PROGRAMADA, DNI_ESTUDIANTE, FECHA_CLASE_PROGRAMADA, HORA_CLASE_PROGRAMADA, CODIGO_NIVEL, CODIGO_CLASE, CODIGO_SALON, ESTADO_CLASE_PROGRAMADA)
VALUES (1, '1234567', TO_DATE('2024-10-30', 'YYYY-MM-DD'), 1, 1, 'CA101', 1, 2);
INSERT INTO CLASES_PROGRAMADAS (CODIGO_CLASE_PROGRAMADA, DNI_ESTUDIANTE, FECHA_CLASE_PROGRAMADA, HORA_CLASE_PROGRAMADA, CODIGO_NIVEL, CODIGO_CLASE, CODIGO_SALON, ESTADO_CLASE_PROGRAMADA)
VALUES (2, '12345678', TO_DATE('2024-10-30', 'YYYY-MM-DD'), 1, 1, 'CA101', 1, 2);
INSERT INTO CLASES_PROGRAMADAS (CODIGO_CLASE_PROGRAMADA, DNI_ESTUDIANTE, FECHA_CLASE_PROGRAMADA, HORA_CLASE_PROGRAMADA, CODIGO_NIVEL, CODIGO_CLASE, CODIGO_SALON, ESTADO_CLASE_PROGRAMADA)
VALUES (3, '87654321', TO_DATE('2024-10-30', 'YYYY-MM-DD'), 1, 1, 'CA101', 1, 2);
INSERT INTO CLASES_PROGRAMADAS (CODIGO_CLASE_PROGRAMADA, DNI_ESTUDIANTE, FECHA_CLASE_PROGRAMADA, HORA_CLASE_PROGRAMADA, CODIGO_NIVEL, CODIGO_CLASE, CODIGO_SALON, ESTADO_CLASE_PROGRAMADA)
VALUES (4, '23456789', TO_DATE('2024-10-30', 'YYYY-MM-DD'), 1, 1, 'CA101', 1, 2);
INSERT INTO CLASES_PROGRAMADAS (CODIGO_CLASE_PROGRAMADA, DNI_ESTUDIANTE, FECHA_CLASE_PROGRAMADA, HORA_CLASE_PROGRAMADA, CODIGO_NIVEL, CODIGO_CLASE, CODIGO_SALON, ESTADO_CLASE_PROGRAMADA)
VALUES (5, '98765432', TO_DATE('2024-10-30', 'YYYY-MM-DD'), 1, 1, 'CA101', 1, 2);

/*
INSERT INTO CUPOS (CODIGO_CUPO, FECHA_CUPO, CODIGO_HORA, CODIGO_NIVEL, CODIGO_SALON, ESTUDIANTES_REGISTRADOS)
VALUES (1, TO_DATE('2024-10-20', 'YYYY-MM-DD'), 1, 1, 1, 5);*/

INSERT INTO EXAMENES (NUMERO_EXAMEN, UNIDADES_EXAMEN, TEMATICA_EXAMEN, CODIGO_CLASE_EXAMEN, CODIGO_NIVEL_EXAMEN)
VALUES (1, 'Unidad 1', 'Vocabulario B�sico', 'CA101', 1);
INSERT INTO EXAMENES (NUMERO_EXAMEN, UNIDADES_EXAMEN, TEMATICA_EXAMEN, CODIGO_CLASE_EXAMEN, CODIGO_NIVEL_EXAMEN)
VALUES (2, 'Unidad 2', 'Conversaciones Simples', 'CA102', 1);

INSERT INTO EXAMENES_ESCRITOS (CODIGO_EXAMEN_ESCRITO, CODIGO_EXAMEN)
VALUES (1, 1);
INSERT INTO EXAMENES_ESCRITOS (CODIGO_EXAMEN_ESCRITO, CODIGO_EXAMEN)
VALUES (2, 2);

INSERT INTO PREGUNTAS (CODIGO_PREGUNTA, CODIGO_EXAMEN_ESCRITO, PREGUNTA)
VALUES (1, 1, '�Qu� significa la palabra "hello"?');
INSERT INTO PREGUNTAS (CODIGO_PREGUNTA, CODIGO_EXAMEN_ESCRITO, PREGUNTA)
VALUES (2, 1, 'Completa la frase: "Good ____."');

INSERT INTO RESPUESTAS (CODIGO_RESPUESTA, CODIGO_PREGUNTA_RESPUESTA, CONTENIDO_RESPUESTA, ACIERTO_RESPUESTA)
VALUES (1, 1, 'Hola', 'true');
INSERT INTO RESPUESTAS (CODIGO_RESPUESTA, CODIGO_PREGUNTA_RESPUESTA, CONTENIDO_RESPUESTA, ACIERTO_RESPUESTA)
VALUES (2, 1, 'Adi�s', 'false');
INSERT INTO RESPUESTAS (CODIGO_RESPUESTA, CODIGO_PREGUNTA_RESPUESTA, CONTENIDO_RESPUESTA, ACIERTO_RESPUESTA)
VALUES (3, 2, 'noon', 'false');
INSERT INTO RESPUESTAS (CODIGO_RESPUESTA, CODIGO_PREGUNTA_RESPUESTA, CONTENIDO_RESPUESTA, ACIERTO_RESPUESTA)
VALUES (4, 2, 'fall', 'false');
INSERT INTO RESPUESTAS (CODIGO_RESPUESTA, CODIGO_PREGUNTA_RESPUESTA, CONTENIDO_RESPUESTA, ACIERTO_RESPUESTA)
VALUES (5, 2, 'morning', 'true');

INSERT INTO ESTADOS_EXAMENES (CODIGO_ESTADO, ESTADO_EXAMEN) VALUES (1, 'Aprobado');
INSERT INTO ESTADOS_EXAMENES (CODIGO_ESTADO, ESTADO_EXAMEN) VALUES (2, 'Reprobado');
INSERT INTO ESTADOS_EXAMENES (CODIGO_ESTADO, ESTADO_EXAMEN) VALUES (3, 'Pendiente');

INSERT INTO EXAMENES_ORALES (CODIGO_EXAMEN_ORAL, CODIGO_EXAMEN, ARCHIVO_URL) VALUES (1, 1, '"C:\Users\ASUS\Downloads\Acta de inicio-1.pdf"');
INSERT INTO EXAMENES_ORALES (CODIGO_EXAMEN_ORAL, CODIGO_EXAMEN, ARCHIVO_URL) VALUES (2, 2, '"C:\Users\ASUS\Downloads\Acta de inicio-1.pdf"');

INSERT INTO RESPUESTAS_EXAMENES_ESCRITOS ( DNI_ESTUDIANTE, CODIGO_EXAMEN_ESCRITO, CODIGO_PREGUNTA, RESPUESTA_ESTUDIANTE, CORRECTA ) VALUES ('1000412597', 1, 1, 1, 'S'); 
INSERT INTO RESPUESTAS_EXAMENES_ESCRITOS ( DNI_ESTUDIANTE, CODIGO_EXAMEN_ESCRITO, CODIGO_PREGUNTA, RESPUESTA_ESTUDIANTE, CORRECTA ) VALUES ('1000412597', 1, 2, 3, 'N');


INSERT INTO NOTAS (CODIGO_NOTA, DNI_ESTUDIANTE, CODIGO_EXAMEN_ORAL, NOTA_EXAMEN_ORAL, FECHA_EVALUACION_EXAMEN_ORAL, CODIGO_EXAMEN_ESCRITO, NOTA_EXAMEN_ESCRITO, FECHA_EVALUACION_EXAMEN_ESCRITO, ESTADO)
VALUES (1, '1234567', 1, NULL, SYSDATE, 1, NULL, SYSDATE, 3);
INSERT INTO NOTAS (CODIGO_NOTA, DNI_ESTUDIANTE, CODIGO_EXAMEN_ORAL, NOTA_EXAMEN_ORAL, FECHA_EVALUACION_EXAMEN_ORAL, CODIGO_EXAMEN_ESCRITO, NOTA_EXAMEN_ESCRITO, FECHA_EVALUACION_EXAMEN_ESCRITO, ESTADO)
VALUES (2, '12345678', 1, NULL, SYSDATE, 1, NULL, SYSDATE, 3);
